# Generated by Django 6.0.1 on 2026-02-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_lat", models.FloatField()),
                ("start_lon", models.FloatField()),
                ("end_lat", models.FloatField()),
                ("end_lon", models.FloatField()),
                ("route_points", models.JSONField()),
                ("total_points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
