# Generated by Django 6.0.3 on 2026-03-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_routelog_options_alter_routelog_route_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routelog',
            name='profile',
            field=models.CharField(choices=[('walking', 'Walking'), ('cycling', 'Cycling'), ('motorcycle', 'Motorcycle'), ('car', 'Car')], default='car', max_length=20),
        ),
    ]
